export { Button, buttonVariants } from './button';
export { Header } from './header-new';
export { HeroWithMockup } from './hero-with-mockup';
export { HeroSection } from './hero-section-2';
export { HeroSectionFull } from './hero-section-full';
export { AnimatedHero } from './animated-hero';
export { ServicesSection } from './services-section';
export { AboutSection } from './about-section';
export { ContactSection } from './contact-section';
export { Footer } from './footer';
export { Glow } from './glow';
export { CertificationsBadges } from './certifications-badges';
export { ClientsSection } from './clients-section';
export { CookieConsent } from './cookie-consent';
